### PR TITLE
Enable plugins folder

### PR DESCRIPTION
**Pull request by LucaCinquini**
## Purpose

- This PR creates a "plugins/" folder that will be used to store code and utilities common to all DAGs

## Proposed Changes

- [ADD] "plugins/" folder to the Airflow custom containers under /opt/airflow/plugins

## Issues

- https://github.com/unity-sds/unity-sps/issues/96

## Testing

- Tested the execution of the "karpenter_test" DAG when using the "unity_sps_utils" library loaded from the plugins folder.

### CODE REVIEW

**Comment by drewm-jpl** [comment]
Thanks Luca. I'm seeing a failure in the unit tests during dag validation:
```
ModuleNotFoundError: No module named 'unity_sps_utils'
```

**Comment by LucaCinquini** [comment]
That module should be part of the "plugins/" folder. Which version of the Docker image is used by the unit tests? It will probably need to be rebuilt.

**Comment by drewm-jpl** [comment]
The unit tests do not utilize a docker image, they are simply static tests.

If we were to use a dag directory structure like this, it seems like we could still utilize our static unit tests:
image

**Comment by LucaCinquini** [comment]
We could... Let me see if I can make the changes.

**Comment by LucaCinquini** [comment]
But it does becomes messy with the "dags/" and "dags-catalog/" folder because we would need to copy selected portions of that "dags/" folder to "/opt/airflow/dags", and not others.

**Comment by drewm-jpl** [comment]
Another option could be to have the custom dag utils/plugins be python package which is pip installed in the Dockerfile. For all of the other dependencies in our DAGs, they are made available to pytest through pip install as part of our pyproject.toml:
https://github.com/unity-sds/unity-sps/blob/develop/pyproject.toml#L34-L45

**Pull request merged**
