### PR TITLE
Commenting jpl-internal ingress

### PR DESCRIPTION
**Pull request by jpl-btlunsfo**
## Purpose

- Commenting out the jpl-internal ingress, and its associated security groups. If necessary, folks can manually re-enable.
  - also switching healthcheck ssm parameters to use shared-services URLs, and adding in the SSM lookups required to fetch those

## Proposed Changes

- ADD shared-services domain lookups (through SSM parameters)
- CHANGE airflow healthcheck and url SSM parameters to point at shared services domain
- CHANGE/comment out the JPL-internal ingress and security group rules

## Issues

- unity-sds/unity-sps#246

## Testing

- Currently deployed at https://www.dev.mdps.mcp.nasa.gov:4443/btl-df1/dev/sps/

### CODE REVIEW

**Review by LucaCinquini — CHANGES_REQUESTED** [review]
Hi @jpl-btlunsfo : I was able to deploy the SPS using this branch without any issues - once you fixed the EKS module. The top-level proxy works fine, but right now if we merged this PR, we wouldn't be able to interact with the Airflow and OGC APIs because we have not yet worked out how to pass the authentication to them.
Can you update this PR so that the Terraform output includes not only the top-level proxy, but also the URLs of the middle and Airflow ALBs? We can use those to temporarily interact with the APIs.

**Comment by jpl-btlunsfo** [comment]
> Can you update this PR so that the Terraform output includes not only the top-level proxy, but also the URLs of the middle and Airflow ALBs? We can use those to temporarily interact with the APIs.

For the first (middle proxy URL) sure, easy enough, but for the airflow ALB? This PR is already disabling the only one we'd be able to access directly- the remaining ALB is specifically locked down by security groups to only talk to the middle proxy. I'll add in the middle proxy one asap, though.

**Comment by LucaCinquini** [comment]
Thanks, that should work

**Comment by jpl-btlunsfo** [comment]
New change should print it all out
```
resources = {
  "buckets" = {
    "airflow_logs" = {
      "bucket" = "btl-df1-dev-sps-airflowlogs"
      "ssm_param_id" = "/btl-df1/dev/sps/processing/airflow/logs"
    }
  }
  "endpoints" = {
    "airflow" = {
      "rest_api" = {
        "ssm_param_id" = "/btl-df1/dev/sps/processing/airflow/api_url"
        "url" = "https://www.dev.mdps.mcp.nasa.gov:4443/btl-df1/dev/sps/api/v1"
      }
      "ui" = {
        "ssm_param_id" = "/btl-df1/dev/sps/processing/airflow/ui_url"
        "url" = "https://www.dev.mdps.mcp.nasa.gov:4443/btl-df1/dev/sps/"
      }
    }
    "ogc_processes" = {
      "rest_api" = {
        "ssm_param_id" = "/btl-df1/dev/sps/processing/ogc_processes/api_url"
        "url" = "https://www.dev.mdps.mcp.nasa.gov:4443/btl-df1/dev/ogc/"
      }
      "ui" = {
        "ssm_param_id" = "/btl-df1/dev/sps/processing/ogc_processes/ui_url"
        "url" = "https://www.dev.mdps.mcp.nasa.gov:4443/btl-df1/dev/ogc/redoc"
      }
    }
  }
  "venue_endpoints" = {
    "airflow" = {
      "rest_api" = {
        "url" = "HTTP://btl-df1-dev-httpd-alb-1474979360.us-west-2.elb.amazonaws.com:8080/btl-df1/dev/sps/api/v1"
      }
      "ui" = {
        "url" = "HTTP://btl-df1-dev-httpd-alb-1474979360.us-west-2.elb.amazonaws.com:8080/btl-df1/dev/sps/"
      }
    }
    "ogc_processes" = {
      "rest_api" = {
        "url" = "HTTP://btl-df1-dev-httpd-alb-1474979360.us-west-2.elb.amazonaws.com:8080/btl-df1/dev/ogc/"
      }
      "ui" = {
        "url" = "HTTP://btl-df1-dev-httpd-alb-1474979360.us-west-2.elb.amazonaws.com:8080/btl-df1/dev/ogc/redoc"
      }
    }
  }
}
```

**Review by LucaCinquini — APPROVED** [review]
Hi @jpl-btlunsfo : this works and will approve it, but is there any way to make the URL protocol "HTTP://..." lowercase?

**Comment by jpl-btlunsfo** [comment]
> make the URL protocol "HTTP://..." lowercase? 

CS's fault. It happens somewhere during their orchestration, but I haven't been able to trace where yet (to file a PR of my own to fix that). There's no functional effect but it's annoying I agree.

**Pull request merged**
