### PR TITLE
Devel luca 1

### PR DESCRIPTION
**Pull request by LucaCinquini**
## Purpose

- This PR enables retrieving some common, venue dependent parameters directly from SSM when the DAG starts, so that they don't have to be specified by the client every time. It makes it possible to run a CWL workflow with the same parameters across all venues.

## Proposed Changes

- [CHANGE] Retrieval of some DAG parameters from SSM (DAPA client id, DAPA API URL, default S3 staging bucket)
- [CHANGE] Add boto3 libraries to Airflow Docker containers, so that Airflow Tasks that run on those can access AWS services (like SSM).

## Issues

- https://github.com/unity-sds/unity-sps/issues/77

## Testing

- Executed the SBG end-to-end workflow on unity-venue-dev successfully

### CODE REVIEW

**Comment by drewm-jpl** [comment]
Seeing the SSM params read in every time the DAG is invoked/processed has me a bit concerned about performance. What do you think about the possibility of having these be environment variables within Airflow? We can include them in the Helm values during deployment time?

We do this already for the Kubernetes namespace of our deployment:
https://github.com/unity-sds/unity-sps/blob/main/airflow/helm/values.tmpl.yaml#L114-L116

Then in the DAG we could read it in like this:
```
from airflow.models import Variable
foo = Variable.get("kubernetes_pipeline_namespace")
```

**Comment by LucaCinquini** [comment]
@drewm-jpl : yes storing the values as Airflow env variables is possible as well, but the disadvantage is that if those values change for any reason, we would need to redeploy SPS.
Why do you think retrieving the SSM parameters every time the DAG starts would cause a degradation in performance? We are talking a fraction of a second versus hours or Task runtime...

**Comment by drewm-jpl** [comment]
Oh sorry, I did not inspect the calls to SSM closely enough. I now see that you've encapsulated the calls in tasks.

My original concern was the following: If you were accessing SSM parameters at the top level of an Airflow DAG (i.e., outside of any task definitions), the API call to retrieve the SSM parameter would indeed be executed every time the DAG is parsed or processed by the Airflow scheduler. This occurs because global code that isn't encapsulated within tasks is executed every time the DAG file is loaded, which happens frequently as Airflow continuously monitors and parses DAG files to reflect any changes and manage scheduling decisions.

Since the API calls are encapsulated in the tasks, I don't see any issues here.

**Comment by LucaCinquini** [comment]
Ah ok, it makes perfect sense, your concern was indeed correct. So are we good then?

**Review by drewm-jpl — APPROVED** [review]
Looks good to me

**Pull request merged**
