### PR TITLE
Adding SBG E2E nightly test config

### PR DESCRIPTION
**Pull request by jpl-btlunsfo**
## Purpose

- Adding a bdd test for the SBG end-to-end DAG

## Proposed Changes

- ADD SBG end-to-end test
- CHANGE pyproject toml to include the "backoff" package

## Issues

- unity-sds/unity-sps#65

## Testing

- Tested with [manual sps deployment](https://app.gitbook.com/o/xZRqGQeQXJ0RP4VMj7Lq/s/UMIRhLdbRQTvMWop8Il9/developer-docs/science-processing/docs/admin-guide/sps-airflow-deployment-with-terraform)
- Test results attached ([test_airflow_sbg_dag_e2e_results.txt](https://github.com/unity-sds/unity-sps/files/15155596/test_airflow_sbg_dag_e2e_results.txt)), status verified in airflow UI 
Screenshot 2024-04-29 at 3 29 48 PM

### CODE REVIEW

**Comment by drewm-jpl** [comment]
This looks good to me. In the future, if we have multiple DAGs that we want to test it might make sense to parameterize the DAG ID in the feature file using a [Scenario Outline](https://cucumber.io/docs/gherkin/reference/). That way we won't have to create a new test/feature for every new DAG.

**Review by drewm-jpl — APPROVED** [review]
This looks good to me. In the future, if we have multiple DAGs that we want to test it might make sense to parameterize the DAG ID in the feature file using a [Scenario Outline](https://cucumber.io/docs/gherkin/reference/). That way we won't have to create a new test/feature for every new DAG.

**Review by LucaCinquini — CHANGES_REQUESTED** [review]
Actually the Pr is very good but I suggest 2 changes:
o Brad you must install the "pre-commit" hook on your laptop so that it will reformat the files appropriately, and make the PR pass the linting
o This should be an integration test, not unit test, so would you mind moving the test to the proper directory?

**Comment by jpl-btlunsfo** [comment]
@LucaCinquini what directory should it go into? as you say, it's not a unit test, so I assumed `unity-test/unit/` was the wrong tree (so I put it under `unity-test/system`). Should I create a `unity-test/integration`?

@drewm-jpl You're right, the only thing that would really change in testing other DAGs would be the DAG post url, and maybe the backoff time limit. I'll see if I can make it scenario outline instead, but I'm not sure how to trigger it. Does pytest_bdd expose those parameters as arguments (for pytest calls)?

**Comment by drewm-jpl** [comment]
@jpl-btlunsfo I don't necessarily think it needs to be done for this PR but for future reference pytest-bdd does support scenario outlines: https://pytest-bdd.readthedocs.io/en/stable/#scenario-outlines

**Comment by drewm-jpl** [comment]
Regarding the location of the tests, SLIM is recommending `/tests/system/integration`
https://yunks128.github.io/slim/docs/guides/software-lifecycle/continuous-testing/#integration-tests

**Comment by jpl-btlunsfo** [comment]
https://github.com/unity-sds/unity-sps/actions/runs/8898825847/job/24436801528 successfully ran, took ~38m

**Review by LucaCinquini — APPROVED** [review]
The test is working for me as well now, please merge into develop, thanks for completing this.

**Pull request merged**
