### PR TITLE
Continuous testing best practices from SLIM

### PR DESCRIPTION
**Pull request by yunks128**
## Purpose

- This pull request aims to improve the CI/CD pipeline by adding automated integration and smoke test result checks and refining the unit test execution process. It also includes the addition of static code analysis and other test configurations.

## Proposed Changes

- [ADD] `.github/dependabot.yml` to schedule dependency updates daily.
- [ADD] `Check Integration Tests Results` step in `.github/workflows/integration_tests.yml` to fail the job if tests fail.
- [CHANGE] Updated `Check Smoke Tests Results` step in `.github/workflows/smoke_tests.yml` to provide detailed feedback on which specific smoke tests failed.
- [CHANGE] Modified `.github/workflows/unit_tests.yml` to add manual workflow dispatch support.
- [ADD] `unity-test/TESTING.md` to provide comprehensive documentation on the testing architecture and processes for the project.

## Issues

- This pull request addresses the need for improved CI/CD pipeline automation and reliability.
- It ensures automated checks for integration and smoke tests, failing the job if any test fails, providing detailed feedback on failures.
- It includes enhancements to support manual workflow dispatch for unit tests.
- Introduces comprehensive documentation for testing architecture and processes, facilitating better understanding and maintenance.

## Testing

- Tested on Ubuntu-latest environment via GitHub Actions.
- Manual checks to ensure the added steps and conditions trigger correctly.

### CODE REVIEW

**Review by drewm-jpl — APPROVED** [review]
@yunks128 Looks good, thanks for your contribution.

**Comment by drewm-jpl** [comment]
@yunks128 can you fix the static analysis failure?

**Comment by drewm-jpl** [comment]
It appears there is still a trailing whitespace issue with the static analysis.

**Comment by yunks128** [comment]
@drewm-jpl, the trailing whitespace issue is fixed, but another error remains. I don't see "--no-fail-on-changed" anywhere, but the error is there. Do you have any idea? Thanks. 
"check-added-large-files: error: unrecognized arguments: --no-fail-on-changed"

**Comment by yunks128** [comment]
@drewm-jpl 
Fixed this problem. no errors now! Thanks!

> @drewm-jpl, the trailing whitespace issue is fixed, but another error remains. I don't see "--no-fail-on-changed" anywhere, but the error is there. Do you have any idea? Thanks. "check-added-large-files: error: unrecognized arguments: --no-fail-on-changed"

**Pull request merged**
