### PR TITLE
Fix the shared-services/venue-services/airflow proxy request issues

### PR DESCRIPTION
**Pull request by jpl-btlunsfo**
## Purpose

- Fix the airflow page redirects by enabling the [proxyfix airflow parameter](https://airflow.apache.org/docs/apache-airflow/stable/howto/run-behind-proxy.html)

## Proposed Changes

- ADD enable_proxy_fix to airflow helm chart YAML

## Issues

- unity-sds/unity-cs#429

## Testing

- Currently deployed in `btl-dd2`/`dev`, accessible at:
  - http://btl-dd2-dev-httpd-alb-1592953208.us-west-2.elb.amazonaws.com:8080/btl-dd2/dev/sps/
  - https://www.dev.mdps.mcp.nasa.gov:4443/btl-dd2/dev/sps/

### CODE REVIEW

**Comment by jpl-btlunsfo** [comment]
The real source of this issue was of course, on the CS side of things- part of the solution here has already been merged in unity-proxy.

The venue-services proxy's ALB was impolitely clearing/disposing of the `X-Forwarded-Host` from any request passing through it- adding the above config option will tell Airflow to use/respect that while crafting URLs.

**Review by LucaCinquini — COMMENTED** [review]
Hi @jpl-btlunsfo : this looks good but I have a couple of questions:
- Where did you set the base_url = ... to instruct Airflow to use that base URL (as from the Airflow reverse proxy instructions)
- What did you have to do to make the proxy work with your personal SPS? I assume that was a manual configuration, can you please add it here for reference?
Thanks, L

**Comment by jpl-btlunsfo** [comment]
1. I didn't; scroll down the page further to this section:
> To ensure that Airflow generates URLs with the correct scheme when running behind a TLS-terminating proxy, you should configure the proxy to set the X-Forwarded-Proto header, and enable the ProxyFix middleware in your airflow.cfg:

  - While we can probably guess the baseurl (/$project/$venue/), it's not necessary to set right now as that pathing is being handled by the venue-proxy at the moment (I could in the future, try to add that to airflow itself, but it might break direct/non-proxy access a bit).
    - This config change is only to make sure airflow respects the port/protocol that is communicated to it from the proxies; otherwise airflow serves up redirects to URLs with ports like 8080 or 5000 when it needs to be 4443 (for shared services).

2. I'm not sure what you mean- are you referring to the shared services proxy? Yeah, that was unfortunately manual, as I've not heard of updates from Brandon yet on cleaning it up, but I followed the [instructions](https://unity-sds.gitbook.io/docs/developer-docs/common-services/docs/maintenance/updating-venue-deployment) [here](https://unity-sds.gitbook.io/docs/developer-docs/common-services/docs/developers-guide/httpd-server-deployment/shared-services-httpd-site-configurations), though they need to be updated at present.

   a. the update being this addition (waiting on Galen to be back so I can find out how to edit these gitbooks)
```
RequestHeader     set "X-Forwarded-Host" "www.dev.mdps.mcp.nasa.gov:4443"
```

**Comment by jpl-btlunsfo** [comment]
Rebased, and redeployed to:
  - http://btl-dd2-dev-httpd-alb-1592953208.us-west-2.elb.amazonaws.com:8080/btl-dd2/dev/sps/
  - https://www.dev.mdps.mcp.nasa.gov:4443/btl-dd2/dev/sps/
  
  @LucaCinquini can you give it a try? let me know the `project`/`venue` you deploy on and I'll handle the management console and shared services config.

**Review by LucaCinquini — COMMENTED** [review]
This PR worked as advertised - the proxies work and the user is presented first with the Cognito login, then the Airflow login. These changes could be combined with the removal of the Airflow login to create a usable end-to-end user experience.
Let's not merge yet until we discuss with the team.

**Pull request merged**
